# Generated by Django 3.2.10 on 2024-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(default='CP000000', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
