# Generated by Django 3.2.10 on 2024-07-05 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0003_auto_20240705_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
