# Generated by Django 3.2.10 on 2024-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20240706_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_amount_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
