# Generated by Django 5.0.6 on 2024-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_remove_gallery_user_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
