# Generated by Django 5.0.6 on 2024-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0012_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='points_credited',
            field=models.BooleanField(default=False),
        ),
    ]
