# Generated by Django 5.0.6 on 2024-08-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0017_alter_coupon_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
