# Generated by Django 5.0.6 on 2024-08-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0019_coupon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.product'),
        ),
    ]
