# Generated by Django 5.0.6 on 2024-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0021_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_in_paise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
